name: GetLit
version: '${project.version}'
main: com.s1survival.getlit.GetLit
api-version: 1.19
authors: [ StumblingGamer ]
description: Lights up caves for players
commands:
  getlit:
    description: allows players to light up caves (Admin use)
    usage: /getlit <radius> <spacing> <top height>
